# Generated by Django 2.0.3 on 2018-03-21 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('cli', models.CharField(max_length=50)),
                ('call_result', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('time_to_answer', models.CharField(max_length=50)),
                ('call_time', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_history',
            },
        ),
    ]
