# Generated by Django 2.0.3 on 2018-03-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_call_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call_history',
            options={'verbose_name': 'Call History', 'verbose_name_plural': 'Call History'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Ambime User', 'verbose_name_plural': 'Ambime Users'},
        ),
        migrations.AlterField(
            model_name='call_history',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='landline1',
            field=models.CharField(max_length=30),
        ),
    ]
