# Generated by Django 2.0.3 on 2018-03-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180322_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='network_provider1',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='network_provider2',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
